name       : lmdb
version    : 0.9.18
release    : 1
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.18.tar.gz : dd35b471d6eea84f48f2feece13d121abf59ef255308b8624a36223ffbdf9989
license    : OLDAP-2.8
component  : programming
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
patterns   :
    - /usr/lib64
build      : |
    cd libraries/liblmdb/
    %make prefix=/usr libdir=%libdir%
install    : |
    cd libraries/liblmdb/
    %make_install prefix=/usr libdir=%libdir%
    rm $installdir%libdir%/*.a