name       : lmdb
version    : 0.9.22
release    : 3
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.22.tar.gz : f3927859882eb608868c8c31586bb7eb84562a40a6bf5cc3e13b6b564641ea28
license    : OLDAP-2.8
component  : programming
libsplit   : no
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-flags.patch
build      : |
    %make prefix=/usr libdir=%libdir% -C libraries/liblmdb
install    : |
    %make_install prefix=/usr libdir=%libdir% -C libraries/liblmdb
    rm $installdir%libdir%/*.a
check      : |
    %make test -C libraries/liblmdb
