name       : lmdb
version    : 0.9.29
release    : 8
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.29.tar.gz : 22054926b426c66d8f2bc22071365df6e35f3aacf19ad943bc6167d4cae3bebb
license    : OLDAP-2.8
component  : programming.library
libsplit   : no
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-flags.patch
build      : |
    %make prefix=/usr libdir=%libdir% -C libraries/liblmdb
install    : |
    %make_install prefix=/usr libdir=%libdir% -C libraries/liblmdb
    rm $installdir%libdir%/*.a
check      : |
    %make test -C libraries/liblmdb
