name       : lmdb
version    : 0.9.23
release    : 4
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.23.tar.gz : abf42e91f046787ed642d9eb21812a5c473f3ba5854124484d16eadbe0aa9c81
license    : OLDAP-2.8
component  : programming
libsplit   : no
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-flags.patch
build      : |
    %make prefix=/usr libdir=%libdir% -C libraries/liblmdb
install    : |
    %make_install prefix=/usr libdir=%libdir% -C libraries/liblmdb
    rm $installdir%libdir%/*.a
check      : |
    %make test -C libraries/liblmdb
