name       : lmdb
version    : 0.9.19
release    : 2
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.19.tar.gz : 108532fb94c6f227558d45be3f3347b52539f0f58290a7bb31ec06c462d05326
license    : OLDAP-2.8
component  : programming
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
patterns   :
    - /usr/lib64
build      : |
    cd libraries/liblmdb/
    %make prefix=/usr libdir=%libdir%
install    : |
    cd libraries/liblmdb/
    %make_install prefix=/usr libdir=%libdir%
    rm $installdir%libdir%/*.a
