name       : lmdb
version    : 0.9.24
release    : 7
source     :
    - https://github.com/LMDB/lmdb/archive/LMDB_0.9.24.tar.gz : 44602436c52c29d4f301f55f6fd8115f945469b868348e3cddaf91ab2473ea26
license    : OLDAP-2.8
component  : programming.library
libsplit   : no
summary    : Lightning memory-mapped database library from Symas
description: |
    Lightning memory-mapped database library from Symas.
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-flags.patch
build      : |
    %make prefix=/usr libdir=%libdir% -C libraries/liblmdb
install    : |
    %make_install prefix=/usr libdir=%libdir% -C libraries/liblmdb
    rm $installdir%libdir%/*.a
check      : |
    %make test -C libraries/liblmdb
